version: 2

sphinx:
  configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements.txt
   - requirements: docs/requirements.txt
build:
   os: "ubuntu-22.04"
   tools:
      python: "3.11"
